spring:
  datasource:
      username: root
      password: 1
      url: jdbc:sqlite:NS.db
      type: com.alibaba.druid.pool.DruidDataSource

      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      #validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: false
      #   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      #filters: stat,wall,log4j
      #maxPoolPreparedStatementPerConnectionSize: 20
      useGlobalDataSourceStat: true
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
      driver-class-name: org.sqlite.JDBC

  jpa:
    hibernate:
      # 更新或者创建数据表结构
      ddl‐auto: update
      # 控制台显示SQL
    show‐sql: true
    database-platform: com.game.itstar.dialect.SQLiteDialect


